apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-gateway-secret
  namespace: gateway
spec:
  refreshInterval: 1m
  secretStoreRefs:
    - name: gcp-store
      kind: SecretStore
  selector:
    secret:
      name: microservices-tls
  template:
    data:
      payload: |
        {
          "tls-key": "{{`{{ index . "tls.key" | toString | b64enc }}`}}",
          "tls-crt": "{{`{{ index . "tls.crt" | toString | b64enc }}`}}",
          "ca-crt": "{{`{{ index . "ca.crt" | toString | b64enc }}`}}"
        }
  data:
    - match:
        secretKey: payload
        remoteRef:
          remoteKey: microservices-tls