apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-gateway-secret
  namespace: gateway
spec:
  refreshInterval: 1m
  secretStoreRefs:
    - name: gcp-store
      kind: SecretStore
  selector:
    secret:
      name: microservices-tls
  template:
    data:
      public-cert: |
        {{ index . "tls.crt" }}
        {{ index . "ca.crt" }}
  data:
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: private-key
    - match:
        secretKey: public-cert
        remoteRef:
          remoteKey: public-cert