apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-gateway-secret
  namespace: gateway
spec:
  refreshInterval: 1m
  secretStoreRefs:
    - name: gcp-store
      kind: SecretStore
  selector:
    secret:
      name: api-key
  data:
    - match:
        secretKey: api-key 
        remoteRef:
          remoteKey: api-key 